config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register'
  }

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: {
    draft: 0,
    published: 1
  }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body

  belongs_to :topic
  has_many :comments, dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog,
                only: %i[show edit update destroy toggle_status]
  layout 'blog'
  access all: %i[show index],
         user: { except: %i[destroy new create update edit toggle_status] },
         site_admin: :all


  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.page(params[:page]).per(5)
    @page_title = 'Katherine\'s Blog'
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.includes(:comments).friendly.find(params[:id])
    @comment = Comment.new

    @page_title = @blog.title
    @seo_keywords = @blog.title
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Your post is live!' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html {
          redirect_to @blog, notice: 'Blog was successfully updated.'
        }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html do
        redirect_to blogs_url, notice: 'Blog was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  def toggle_status
    @blog.draft? ? @blog.published! : @blog.draft!
    redirect_to blogs_url, notice: 'Post status updated'
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def blog_params
    params.require(:blog).permit(:title, :body)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar(user)
    image_tag(
        "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}",
        width: 40
    )
  end
end

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title, blog %></h2>
  <p class="blog-post-meta">
    <%= distance_of_time_in_words Time.now, blog.created_at %> by <a href="#">Katherine</a>
  </p>
  <% if logged_in? :site_admin %>
    <p class="blog-post-meta">
      <%= link_to "(#{blog.status})", toggle_status_blog_path(blog) if logged_in? :site_admin %>
      <%= link_to 'Edit', edit_blog_path(blog) if logged_in? :site_admin %>
      <%= link_to 'Destroy',
                  blog, method: :delete, data: { confirm: 'Are you sure?' } if logged_in? :site_admin
      %>
    </p>
    <% end %>
  <div class="blog-body">
    <%= blog.body %>
  </div>
</div><!-- /.blog-post -->

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= form.label :title, class: 'sr-only' %>
    <%= form.text_field :title, class: 'form-control', placeholder: 'Title' %>
  </div>

  <div class="form-group">
    <%= form.label :body, class: 'sr-only' %>
    <%= form.text_area :body, class: 'form-control',
                       rows: 10,
                       placeholder: 'Content' %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<%= render @blogs %>
<%= paginate @blogs %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<div class="col-sm-8">
  <h2><%= @blog.title %></h2>
  <div class="blog-body">
    <%= @blog.body %>
    <div class="mb-2">
      <%= link_to 'Edit', edit_blog_path(@blog) if logged_in? :site_admin %> |
      <%= link_to 'Back', blogs_path %>
    </div>
  </div>
  <!--Start of comment form  -->
  <%= render 'comments/comment_form' %>
  <!--End of comment form  -->


  <!--Start of comments -->
  <div id="comments" data-blog-id="<%= @blog.id %>">
    <%= render @blog.comments %>
  </div>

  <!--End of comments -->
</div>