config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register'
  }

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body

  has_many :technologies
  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs|
                                  attrs['name'].blank?
                                }

  def self.by_position
    order 'position ASC'
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: %i[show edit update destroy]
  layout 'portfolio'
  access all: %i[show index],
         user: { except: %i[destroy new create update edit, sort] },
         site_admin: :all
  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each_pair do |_, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    head :ok
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    respond_to do |format|
      if @portfolio_item.save
        format.html do
          redirect_to portfolios_path,
                      notice: 'Your new project is live!'
        end
      else
        format.html { render :new }
      end
    end
  end

  def edit
    3.times { @portfolio_item.technologies.build }
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params) then
        format.html { redirect_to portfolios_path, notice: 'Your project has been updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show; end

  def destroy
    @portfolio_item.destroy

    respond_to do |format|
      format.html do
        redirect_to portfolios_path, notice: 'Your project has been removed.'
      end
    end
  end

  private


  def portfolio_params
    params.require(:portfolio)
          .permit :title,
                  :subtitle,
                  :body,
                  :main_image,
                  :thumb_image,
                  technologies_attributes: %i[id name _destroy]
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.friendly.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  extend ActiveSupport::Concern

  def image_generator(height, width)
    "http://via.placeholder.com/#{height}x#{width}"
  end

  def portfolio_img(img, type)
    if img.file.nil?
      if type == 'thumb'
        image_generator(350, 200)
      else
        image_generator(600, 400)
      end
    else
      img.url
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio_item, local: true) do |form| %>
  <% if portfolio_item.errors.any? %>
    <% portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: 'form-control'%>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload Main Image <%= form.file_field :main_image, style: 'display:none;' %>
        </label>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload Thumb Image <%= form.file_field :thumb_image, style: 'display:none;' %>
        </label>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control', rows: 10 %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h3>Technologies Used:</h3>
      <div>
        <%= form.fields_for :technologies do |tech_form| %>
          <%= render 'technology_fields', f: tech_form %>
        <% end %>
        <div>
          <%= link_to_add_association 'Add Technology', form, :technologies %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= form.submit class: 'btn btn-primary btn-lg btn-block' %>
  </div>
<% end %>

app/views/portfolios/_portfolio.html.erb
<div class="col-md-4 align-items-center">
  <div class="card mb-4 box-shadow" data-id="<%= portfolio.id %>">
    <%= image_tag portfolio_img(portfolio.thumb_image, 'thumb'), class: 'card-img-top' %>
    <div class="card-body d-flex justify-content-center">
      <p class="card-text mb-0">
        <%= link_to portfolio.title, portfolio_show_path(portfolio) %>
        - <span><%= portfolio.subtitle %></span>
      </p>
    </div>
  </div>

</div>

app/views/portfolios/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View All Projects", portfolios_path %>
    </p>
    <p class="mb-0"><%= copyright_generator %></p>
    <p>
      <a href="#">Back to Top</a>
    </p>
  </div>
</footer>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove', f %>
</div>

app/views/portfolios/edit.html.erb
<div class="container pt-3">
  <h1 class="text-center mb-5">Edit this Project</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<p class="text-center pt-3">
  <%= link_to "Add a new Project", new_portfolio_path if logged_in? :site_admin%>
</p>
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row <%= 'sortable' if logged_in? :site_admin %>">
      <%= render @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container pt-3">
  <h1 class="text-center mb-5">Add a new Project to your Portfolio</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container p-3">
  <div class="row align-items-center">
    <div class="col-md-7">
      <%= image_tag portfolio_img(@portfolio_item.main_image, 'main'), width:'100%' %>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>
      <hr>
      <p><em><%= @portfolio_item.subtitle %></em></p>
      <p><%= @portfolio_item.body %></p>

      <hr>
      <h3>Technologies Used:</h3>
      <% @portfolio_item.technologies.each do |t| %>
        <p><%= t.name %></p>
      <% end %>

      <% if logged_in? :site_admin %>
        <%= link_to 'Edit Project',
                    edit_portfolio_path(@portfolio_item),
                    class: 'btn btn-danger'
        %>
      <% end %>
    </div>
  </div>
</div>