config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register'
  }

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto app-footer">
  <div class="inner">
    <p><%= copyright_generator %></p>
    <!--      <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>-->
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Katherine Ebel</h3>
    <nav class="nav nav-masthead justify-content-center">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_nav.html.erb
<header class="blog-header py-3">
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-4 pt-1">
      <a class="text-muted" href="#">Subscribe</a>
      <% if logged_in? :site_admin %>
        <%= link_to 'Add Blog Post', new_blog_path,
                  class: 'text-muted ml-3'
        %>
      <% end %>
    </div>
    <div class="col-4 text-center">
      <a class="blog-header-logo text-dark" href="#">Katherine's Blog</a>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">
      <a class="text-muted" href="#">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3">
          <circle cx="10.5" cy="10.5" r="7.5"></circle>
          <line x1="21" y1="21" x2="15.8" y2="15.8"></line>
        </svg>
      </a>
      <%= link_to "Sign up",
                  new_user_registration_path,
                  class: 'btn btn-sm btn-outline-secondary'
      %>
    </div>
  </div>
</header>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis
      euismod. Cras mattis consectetur purus sit amet fermentum. Aenean
      lacinia bibendum nulla sed consectetur.</p>
  </div>

  <div class="p-3">
    <h4 class="font-italic">Archives</h4>
    <ol class="list-unstyled mb-0">
      <li><a href="#">March 2014</a></li>
      <li><a href="#">February 2014</a></li>
      <li><a href="#">January 2014</a></li>
      <li><a href="#">December 2013</a></li>
      <li><a href="#">November 2013</a></li>
      <li><a href="#">October 2013</a></li>
      <li><a href="#">September 2013</a></li>
      <li><a href="#">August 2013</a></li>
      <li><a href="#">July 2013</a></li>
      <li><a href="#">June 2013</a></li>
      <li><a href="#">May 2013</a></li>
      <li><a href="#">April 2013</a></li>
    </ol>
  </div>

  <div class="p-3">
    <h4 class="font-italic">Social Links</h4>
    <ol class="list-unstyled d-flex justify-content-around">
      <li><a href="#"><%= fa_icon "github", class: 'fa-2x'  %></a></li>
      <li><a href="#"><%= fa_icon "twitter", class: 'fa-2x' %></a></li>
      <li><a href="#"><%= fa_icon "facebook", class: 'fa-2x' %></a></li>
      <li><a href="#"><%= fa_icon "linkedin", class: 'fa-2x' %></a></li>
    </ol>
  </div>
</aside><!-- /.blog-sidebar -->

app/views/shared/_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Cover</h3>
    <nav class="nav nav-masthead justify-content-center">
      <%= nav_helper 'nav-link', 'a' %>
    </nav>
  </div>
</header>

app/views/shared/_portfolio_header.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-5 col-md-5 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-7  py-4">
          <h4 class="text-white">Get in touch</h4>
          <ul class="list-unstyled d-flex justify-content-between">
            <li><a href="#" class="text-white"><%= fa_icon "github", class: 'fa-2x'  %></a></li>
            <li><a href="#" class="text-white"><%= fa_icon "twitter", class: 'fa-2x' %></a></li>
            <li><a href="#" class="text-white"><%= fa_icon "facebook", class: 'fa-2x' %></a></li>
            <li><a href="#" class="text-white"><%= fa_icon "linkedin", class: 'fa-2x' %></a></li>
            <li><a href="#" class="text-white"><%= fa_icon "envelope", class: 'fa-2x' %></a></li>
          </ul>
          <h4 class="text-white">Explore</h4>
          <nav class="nav d-flex-nowrap list-unstyled justify-content-between">
            <%= nav_helper 'text-white nav-link', 'span' %>
            <%= login_helper 'text-white nav-link' %>
          </nav>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark box-shadow">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
        <strong>Katherine Ebel</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

app/views/shared/_portfolios_jumbotron.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Portfolio Items</h1>
    <p class="lead text-muted">Some of the projects I have worked on in the past.</p>
    <p>
      <%= link_to 'Want to Work With Me?', contact_path, class: 'btn btn-primary my-2' %>
      <%= link_to 'Check Out My Blog', blogs_path, class: 'btn btn-secondary my-2' %>
    </p>
  </div>
</section>